words = (
    "afghanistan", "albania", "algeria", "andorra", "angola", "argentina", "armenia", "australia", "austria",
    "azerbaijan", "bahamas", "bahrain", "bangladesh", "barbados", "belarus", "belgium", "belize", "benin", "bhutan",
    "bolivia", "botswana", "brazil", "brunei", "bulgaria", "burundi", "cambodia", "cameroon", "canada", "chad",
    "chile", "china", "colombia", "comoros", "congo", "croatia", "cuba", "cyprus", "denmark", "djibouti",
    "dominica", "ecuador", "egypt", "eritrea", "estonia", "eswatini", "ethiopia", "fiji", "finland", "france",
    "gabon", "gambia", "georgia", "germany", "ghana", "greece", "grenada", "guatemala", "guinea", "guyana",
    "haiti", "honduras", "hungary", "iceland", "india", "indonesia", "iran", "iraq", "ireland", "israel",
    "italy", "jamaica", "japan", "jordan", "kazakhstan", "kenya", "kiribati", "kosovo", "kuwait", "kyrgyzstan",
    "laos", "latvia", "lebanon", "lesotho", "liberia", "libya", "lithuania", "luxembourg", "madagascar", "malawi",
    "malaysia", "maldives", "mali", "malta", "mauritania", "mauritius", "mexico", "micronesia", "moldova", "monaco",
    "mongolia", "montenegro", "morocco", "mozambique", "myanmar", "namibia", "nauru", "nepal", "netherlands", "nicaragua",
    "niger", "nigeria", "norway", "oman", "pakistan", "palau", "panama", "paraguay", "peru", "philippines",
    "poland", "portugal", "qatar", "romania", "russia", "rwanda", "samoa", "senegal", "serbia", "seychelles",
    "singapore", "slovakia", "slovenia", "somalia", "spain", "sudan", "suriname", "sweden", "switzerland", "syria",
    "taiwan", "tajikistan", "tanzania", "thailand", "togo", "tonga", "tunisia", "turkey", "turkmenistan", "tuvalu",
    "uganda", "ukraine", "uruguay", "uzbekistan", "vanuatu", "venezuela", "vietnam", "yemen", "zambia", "zimbabwe",
    "carrot", "broccoli", "asparagus", "cauliflower", "corn", "cucumber", "eggplant", "lettuce", "mushrooms", "onion",
    "potato", "pumpkin", "tomato", "beetroot", "peas", "zucchini", "radish", "artichoke", "leek", "cabbage",
    "celery", "chili", "garlic", "basil", "coriander", "parsley", "dill", "rosemary", "oregano", "cinnamon",
    "saffron", "bean", "chickpea", "lentil", "apple", "apricot", "avocado", "banana", "blackberry", "blueberry",
    "cherry", "coconut", "fig", "grape", "grapefruit", "kiwifruit", "lemon", "lime", "lychee", "mandarin",
    "mango", "melon", "nectarine", "orange", "papaya", "peach", "pear", "pineapple", "plum", "pomegranate",
    "quince", "raspberry", "strawberry", "watermelon", "bread", "milk", "cheese", "butter", "yogurt", "cream",
    "egg", "chicken", "beef", "pork", "lamb", "fish", "shrimp", "crab", "lobster", "oyster",
    "clam", "mussel", "scallop", "squid", "octopus", "tofu", "tempeh", "seitan", "rice", "pasta",
    "noodle", "bagel", "croissant", "muffin", "pancake", "waffle", "cereal", "granola", "oatmeal", "quinoa",
    "barley", "bulgur", "couscous", "polenta", "grits", "cornmeal", "flour", "sugar", "salt", "pepper",
    "vinegar", "ketchup", "mustard", "mayonnaise", "honey", "jam", "jelly", "peanutbutter", "almondbutter", "cashewbutter",
    "hazelnutbutter", "walnutbutter", "pecanbutter", "macadamiabutter", "pistachiobutter", "sunflowerbutter", "pumpkinbutter", "sesamebutter", "tahini", "oliveoil",
    "coconutoil", "avocadooil", "canolaoil", "vegetableoil", "peanutoil", "sesameoil", "sunfloweroil", "grapeseedoil", "walnutoil", "almondoil",
    "hazelnutoil", "macadamiaoil", "pistachiooil", "pecanoil", "pumpkinoil", "flaxseedoil", "hempoil", "chiaoil", "butter", "ghee",
    "lard", "shortening", "margarine", "coconutbutter", "cocoabutter", "sheabutter", "palmoil", "palmkerneloil", "babassuoil", "cup",
    "plate", "bowl", "spoon", "fork", "knife", "chopsticks", "napkin", "straw", "toothpick", "skewer",
    "tongs", "whisk", "spatula", "ladle", "peeler", "grater", "zester", "juicer", "blender", "foodprocessor",
    "mixer", "toaster", "microwave", "oven", "stove", "grill", "barbecue", "smoker", "deepfryer", "airfryer",
    "pressurecooker", "slowcooker", "ricecooker", "breadmaker", "coffeemaker", "espressomachine", "kettle", "teapot", "mug", "glass",
    "pitcher", "jug", "bottle", "thermos", "cooler", "icetray", "icebucket", "icecreammaker", "popcornmaker", "wafflemaker",
    "pancakemaker", "crepemaker", "fonduepot", "chocolatefountain", "cottoncandymachine", "snowconemachine", "slushiemachine", "yogurtmaker", "cheesemaker", "butterchurn",
    "meatgrinder", "sausagestuffer", "pastamaker", "pizzaoven", "tandooroven", "rotisserie", "smoker", "dehydrator", "vacuumsealer", "canopener",
    "bottleopener", "corkscrew", "jaropener", "nutcracker", "garlicpress", "lemonsqueezer", "applecorer", "melonballer", "icecreamscoop", "pizzacutter","arcane","ekko",
    "pastrycutter", "doughscraper", "benchscraper", "rollingpin", "pastrybrush", "bastingbrush"
)