words = (
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia", "Australia", "Austria",
    "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
    "Bolivia", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burundi", "Cambodia", "Cameroon", "Canada", "Chad",
    "Chile", "China", "Colombia", "Comoros", "Congo", "Croatia", "Cuba", "Cyprus", "Denmark", "Djibouti",
    "Dominica", "Ecuador", "Egypt", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France",
    "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guyana",
    "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
    "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania", "Luxembourg", "Madagascar", "Malawi",
    "Malaysia", "Maldives", "Mali", "Malta", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco",
    "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Nicaragua",
    "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Paraguay", "Peru", "Philippines",
    "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Samoa", "Senegal", "Serbia", "Seychelles",
    "Singapore", "Slovakia", "Slovenia", "Somalia", "Spain", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
    "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
    "Uganda", "Ukraine", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe",
    "carrot", "broccoli", "asparagus", "cauliflower", "corn", "cucumber", "eggplant", "lettuce", "mushrooms", "onion",
    "potato", "pumpkin", "tomato", "beetroot", "peas", "zucchini", "radish", "artichoke", "leek", "cabbage",
    "celery", "chili", "garlic", "basil", "coriander", "parsley", "dill", "rosemary", "oregano", "cinnamon",
    "saffron", "bean", "chickpea", "lentil", "apple", "apricot", "avocado", "banana", "blackberry", "blueberry",
    "cherry", "coconut", "fig", "grape", "grapefruit", "kiwifruit", "lemon", "lime", "lychee", "mandarin",
    "mango", "melon", "nectarine", "orange", "papaya", "peach", "pear", "pineapple", "plum", "pomegranate",
    "quince", "raspberry", "strawberry", "watermelon", "bread", "milk", "cheese", "butter", "yogurt", "cream",
    "egg", "chicken", "beef", "pork", "lamb", "fish", "shrimp", "crab", "lobster", "oyster",
    "clam", "mussel", "scallop", "squid", "octopus", "tofu", "tempeh", "seitan", "rice", "pasta",
    "noodle", "bagel", "croissant", "muffin", "pancake", "waffle", "cereal", "granola", "oatmeal", "quinoa",
    "barley", "bulgur", "couscous", "polenta", "grits", "cornmeal", "flour", "sugar", "salt", "pepper",
    "vinegar", "ketchup", "mustard", "mayonnaise", "honey", "jam", "jelly", "peanutbutter", "almondbutter", "cashewbutter",
    "hazelnutbutter", "walnutbutter", "pecanbutter", "macadamiabutter", "pistachiobutter", "sunflowerbutter", "pumpkinbutter", "sesamebutter", "tahini", "oliveoil",
    "coconutoil", "avocadooil", "canolaoil", "vegetableoil", "peanutoil", "sesameoil", "sunfloweroil", "grapeseedoil", "walnutoil", "almondoil",
    "hazelnutoil", "macadamiaoil", "pistachiooil", "pecanoil", "pumpkinoil", "flaxseedoil", "hempoil", "chiaoil", "butter", "ghee",
    "lard", "shortening", "margarine", "coconutbutter", "cocoabutter", "sheabutter", "palmoil", "palmkerneloil", "babassuoil", "cup",
    "plate", "bowl", "spoon", "fork", "knife", "chopsticks", "napkin", "straw", "toothpick", "skewer",
    "tongs", "whisk", "spatula", "ladle", "peeler", "grater", "zester", "juicer", "blender", "foodprocessor",
    "mixer", "toaster", "microwave", "oven", "stove", "grill", "barbecue", "smoker", "deepfryer", "airfryer",
    "pressurecooker", "slowcooker", "ricecooker", "breadmaker", "coffeemaker", "espressomachine", "kettle", "teapot", "mug", "glass",
    "pitcher", "jug", "bottle", "thermos", "cooler", "icetray", "icebucket", "icecreammaker", "popcornmaker", "wafflemaker",
    "pancakemaker", "crepemaker", "fonduepot", "chocolatefountain", "cottoncandymachine", "snowconemachine", "slushiemachine", "yogurtmaker", "cheesemaker", "butterchurn",
    "meatgrinder", "sausagestuffer", "pastamaker", "pizzaoven", "tandooroven", "rotisserie", "smoker", "dehydrator", "vacuumsealer", "canopener",
    "bottleopener", "corkscrew", "jaropener", "nutcracker", "garlicpress", "lemonsqueezer", "applecorer", "melonballer", "icecreamscoop", "pizzacutter",
#     "pastrycutter", "doughscraper", "benchscraper", "rollingpin", "pastrybrush", "bastingbrush"
)